### ISSUE TITLE
Setting a subject inactive in a coursepass throws exception

### ISSUE THREAD

**Issue by BlackDiamondWing** [derstaubige/jTimetable#6]
SQL-Statement for updating T_CoursePassLecturerSubject seems to be wrong (this should be similaar/ same as issue #5):
![image](https://user-images.githubusercontent.com/105712615/221851135-6e842e04-95a7-45ec-a477-35ebf503e101.png)

**Comment by BlackDiamondWing** [comment]
Mistake in sql query fixed.

Inform user that there might be lessons for the subject in an existing timetable.

**Comment by derstaubige** [comment]
seamed fixxed
