### ISSUE TITLE
Saving lecturers timetable to file can't handle empty timeslots

### ISSUE THREAD

**Issue by BlackDiamondWing** [derstaubige/jTimetable#9]
![image](https://user-images.githubusercontent.com/105712615/226320381-326f192d-0a96-4aa7-8839-1ef576a3a4e2.png)

![image](https://user-images.githubusercontent.com/105712615/226320205-56a814f4-1292-47b1-aa4f-c5e6967c25df.png)

--> Last day is missing in file

**Comment by derstaubige** [comment]
should be fixed with commit 137c7778d067840f24c8df995c3d0c17a276e600
